build:
  maxIssues: 0  # Strict: no issues allowed

complexity:
  active: true
  ComplexMethod:
    active: true
    threshold: 15  # Cyclomatic complexity limit
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
  LongMethod:
    active: true
    threshold: 60  # Maximum lines per function
  LongParameterList:
    active: true
    functionThreshold: 6  # Maximum parameters
    constructorThreshold: 7
    ignoreDefaultParameters: false
  LargeClass:
    active: true
    threshold: 400  # Maximum lines per class
  ComplexCondition:
    active: true
    threshold: 4  # Maximum conditions in if/when
  TooManyFunctions:
    active: true
    thresholdInFiles: 25  # Maximum functions per file
    thresholdInClasses: 25  # Maximum functions per class
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false
  NestedBlockDepth:
    active: true
    threshold: 4  # Maximum nesting depth

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - Exception
      - Throwable
      - RuntimeException
  SwallowedException:
    active: true
    ignoredExceptionTypes:
      - InterruptedException
      - NumberFormatException
      - ParseException
  ThrowingExceptionsWithoutMessageOrCause:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
  ConstantNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

performance:
  active: true
  SpreadOperator:
    active: true
  ForEachOnRange:
    active: true

potential-bugs:
  active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  UnusedUnaryOperator:
    active: true
  WrongEqualsTypeParameter:
    active: true

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 140
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true
  MagicNumber:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/build/**']
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignoreRanges: true
    ignoreExtensionFunctions: true
  ReturnCount:
    active: true
    max: 3  # Maximum return statements per function
    excludedFunctions: 'equals'
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: true
  ForbiddenComment:
    active: true
    values:
      - 'FIXME:'
      - 'STOPSHIP:'
      - 'TODO:'  # Enforce using GitHub issues instead
    allowedPatterns: ''
  UnnecessaryAbstractClass:
    active: true
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID)'
